import pandas as pd
import dataframe

data = pd.read_csv(r'D:\Academic\Level 4 - Semester 1\Research Project\Categorized Data\Skills\Vector.csv')

df = pd.DataFrame(data)


Org1 = {'Software Engineering':1,
        'Quality Assurance':2,
        'Business Analysis':3,
        'Networking':4,
        'Management':5,
        'Research':6,
        'Lecturing':7,
        'Database':8,
        'Data Science':9,
        'Computer Science':10,
        'Information Technology':11,
        'Computer Architecture':12,
        'Distributed System':13,
        'Cloud Computing':14,
        'Data Structures and Algorithms':15,
        'Programming Languages':16,
        'Mathematics':17,
        'Operating Systems':18,
        'Multimedia, Animation and Graphic Design':19,
        'Cyber Security':20,
        'Information System':21,
        'Artificial Intelligence':22,
        'Bio-informatics':23,
        'Telecommunication':24,
        'Embedded System':25,
        'Marketing and E-Commerce':26,
        'E-Governance':27,
        'GIS':28,
        'HCI':29,
        'Big Data':30,
        'Other':0 }

df.Org1 = [Org1[item] for item in df.Org1]
#print(df)

Org2 = {'Software Engineering':1,
        'Quality Assurance':2,
        'Business Analysis':3,
        'Networking':4,
        'Management':5,
        'Research':6,
        'Lecturing':7,
        'Database':8,
        'Data Science':9,
        'Computer Science':10,
        'Information Technology':11,
        'Computer Architecture':12,
        'Distributed System':13,
        'Cloud Computing':14,
        'Data Structures and Algorithms':15,
        'Programming Languages':16,
        'Mathematics':17,
        'Operating Systems':18,
        'Multimedia, Animation and Graphic Design':19,
        'Cyber Security':20,
        'Information System':21,
        'Artificial Intelligence':22,
        'Bio-informatics':23,
        'Telecommunication':24,
        'Embedded System':25,
        'Marketing and E-Commerce':26,
        'E-Governance':27,
        'GIS':28,
        'HCI':29,
        'Big Data':30,
        'Other':0 }

df.Org2 = [Org2[item] for item in df.Org2]
#print(df)

Org3 = {'Software Engineering':1,
        'Quality Assurance':2,
        'Business Analysis':3,
        'Networking':4,
        'Management':5,
        'Research':6,
        'Lecturing':7,
        'Database':8,
        'Data Science':9,
        'Computer Science':10,
        'Information Technology':11,
        'Computer Architecture':12,
        'Distributed System':13,
        'Cloud Computing':14,
        'Data Structures and Algorithms':15,
        'Programming Languages':16,
        'Mathematics':17,
        'Operating Systems':18,
        'Multimedia, Animation and Graphic Design':19,
        'Cyber Security':20,
        'Information System':21,
        'Artificial Intelligence':22,
        'Bio-informatics':23,
        'Telecommunication':24,
        'Embedded System':25,
        'Marketing and E-Commerce':26,
        'E-Governance':27,
        'GIS':28,
        'HCI':29,
        'Big Data':30,
        'Other':0 }

df.Org3 = [Org3[item] for item in df.Org3]
#print(df)

Edu1 = {'Software Engineering':1,
        'Quality Assurance':2,
        'Business Analysis':3,
        'Networking':4,
        'Management':5,
        'Research':6,
        'Lecturing':7,
        'Database':8,
        'Data Science':9,
        'Computer Science':10,
        'Information Technology':11,
        'Computer Architecture':12,
        'Distributed System':13,
        'Cloud Computing':14,
        'Data Structures and Algorithms':15,
        'Programming Languages':16,
        'Mathematics':17,
        'Operating Systems':18,
        'Multimedia, Animation and Graphic Design':19,
        'Cyber Security':20,
        'Information System':21,
        'Artificial Intelligence':22,
        'Bio-informatics':23,
        'Telecommunication':24,
        'Embedded System':25,
        'Marketing and E-Commerce':26,
        'E-Governance':27,
        'GIS':28,
        'HCI':29,
        'Big Data':30,
        'Other':0 }

df.Edu1 = [Edu1[item] for item in df.Edu1]
#print(df)

Edu2 = {'Software Engineering':1,
        'Quality Assurance':2,
        'Business Analysis':3,
        'Networking':4,
        'Management':5,
        'Research':6,
        'Lecturing':7,
        'Database':8,
        'Data Science':9,
        'Computer Science':10,
        'Information Technology':11,
        'Computer Architecture':12,
        'Distributed System':13,
        'Cloud Computing':14,
        'Data Structures and Algorithms':15,
        'Programming Languages':16,
        'Mathematics':17,
        'Operating Systems':18,
        'Multimedia, Animation and Graphic Design':19,
        'Cyber Security':20,
        'Information System':21,
        'Artificial Intelligence':22,
        'Bio-informatics':23,
        'Telecommunication':24,
        'Embedded System':25,
        'Marketing and E-Commerce':26,
        'E-Governance':27,
        'GIS':28,
        'HCI':29,
        'Big Data':30,
        'Other':0 }

df.Edu2 = [Edu2[item] for item in df.Edu2]


Skill1 = {'Software Engineering':1,
        'Quality Assurance':2,
        'Business Analysis':3,
        'Networking':4,
        'Management':5,
        'Research':6,
        'Lecturing':7,
        'Database':8,
        'Data Science':9,
        'Computer Science':10,
        'Information Technology':11,
        'Computer Architecture':12,
        'Distributed System':13,
        'Cloud Computing':14,
        'Data Structures and Algorithms':15,
        'Programming Languages':16,
        'Mathematics':17,
        'Operating Systems':18,
        'Multimedia, Animation and Graphic Design':19,
        'Cyber Security':20,
        'Information System':21,
        'Artificial Intelligence':22,
        'Bio-informatics':23,
        'Telecommunication':24,
        'Embedded System':25,
        'Marketing and E-Commerce':26,
        'E-Governance':27,
        'GIS':28,
        'HCI':29,
        'Big Data':30,
        'Other':0 }

df.Skill1 = [Skill1[item] for item in df.Skill1]


Skill2 = {'Software Engineering':1,
        'Quality Assurance':2,
        'Business Analysis':3,
        'Networking':4,
        'Management':5,
        'Research':6,
        'Lecturing':7,
        'Database':8,
        'Data Science':9,
        'Computer Science':10,
        'Information Technology':11,
        'Computer Architecture':12,
        'Distributed System':13,
        'Cloud Computing':14,
        'Data Structures and Algorithms':15,
        'Programming Languages':16,
        'Mathematics':17,
        'Operating Systems':18,
        'Multimedia, Animation and Graphic Design':19,
        'Cyber Security':20,
        'Information System':21,
        'Artificial Intelligence':22,
        'Bio-informatics':23,
        'Telecommunication':24,
        'Embedded System':25,
        'Marketing and E-Commerce':26,
        'E-Governance':27,
        'GIS':28,
        'HCI':29,
        'Big Data':30,
        'Other':0 }

df.Skill2 = [Skill2[item] for item in df.Skill2]


Skill3 = {'Software Engineering':1,
        'Quality Assurance':2,
        'Business Analysis':3,
        'Networking':4,
        'Management':5,
        'Research':6,
        'Lecturing':7,
        'Database':8,
        'Data Science':9,
        'Computer Science':10,
        'Information Technology':11,
        'Computer Architecture':12,
        'Distributed System':13,
        'Cloud Computing':14,
        'Data Structures and Algorithms':15,
        'Programming Languages':16,
        'Mathematics':17,
        'Operating Systems':18,
        'Multimedia, Animation and Graphic Design':19,
        'Cyber Security':20,
        'Information System':21,
        'Artificial Intelligence':22,
        'Bio-informatics':23,
        'Telecommunication':24,
        'Embedded System':25,
        'Marketing and E-Commerce':26,
        'E-Governance':27,
        'GIS':28,
        'HCI':29,
        'Big Data':30,
        'Other':0 }

df.Skill3 = [Skill3[item] for item in df.Skill3]


Skill4 = {'Software Engineering':1,
        'Quality Assurance':2,
        'Business Analysis':3,
        'Networking':4,
        'Management':5,
        'Research':6,
        'Lecturing':7,
        'Database':8,
        'Data Science':9,
        'Computer Science':10,
        'Information Technology':11,
        'Computer Architecture':12,
        'Distributed System':13,
        'Cloud Computing':14,
        'Data Structures and Algorithms':15,
        'Programming Languages':16,
        'Mathematics':17,
        'Operating Systems':18,
        'Multimedia, Animation and Graphic Design':19,
        'Cyber Security':20,
        'Information System':21,
        'Artificial Intelligence':22,
        'Bio-informatics':23,
        'Telecommunication':24,
        'Embedded System':25,
        'Marketing and E-Commerce':26,
        'E-Governance':27,
        'GIS':28,
        'HCI':29,
        'Big Data':30,
        'Other':0 }

df.Skill4 = [Skill4[item] for item in df.Skill4]


Skill5 = {'Software Engineering':1,
        'Quality Assurance':2,
        'Business Analysis':3,
        'Networking':4,
        'Management':5,
        'Research':6,
        'Lecturing':7,
        'Database':8,
        'Data Science':9,
        'Computer Science':10,
        'Information Technology':11,
        'Computer Architecture':12,
        'Distributed System':13,
        'Cloud Computing':14,
        'Data Structures and Algorithms':15,
        'Programming Languages':16,
        'Mathematics':17,
        'Operating Systems':18,
        'Multimedia, Animation and Graphic Design':19,
        'Cyber Security':20,
        'Information System':21,
        'Artificial Intelligence':22,
        'Bio-informatics':23,
        'Telecommunication':24,
        'Embedded System':25,
        'Marketing and E-Commerce':26,
        'E-Governance':27,
        'GIS':28,
        'HCI':29,
        'Big Data':30,
        'Other':0 }

df.Skill5 = [Skill5[item] for item in df.Skill5]

Skill6 = {'Software Engineering':1,
        'Quality Assurance':2,
        'Business Analysis':3,
        'Networking':4,
        'Management':5,
        'Research':6,
        'Lecturing':7,
        'Database':8,
        'Data Science':9,
        'Computer Science':10,
        'Information Technology':11,
        'Computer Architecture':12,
        'Distributed System':13,
        'Cloud Computing':14,
        'Data Structures and Algorithms':15,
        'Programming Languages':16,
        'Mathematics':17,
        'Operating Systems':18,
        'Multimedia, Animation and Graphic Design':19,
        'Cyber Security':20,
        'Information System':21,
        'Artificial Intelligence':22,
        'Bio-informatics':23,
        'Telecommunication':24,
        'Embedded System':25,
        'Marketing and E-Commerce':26,
        'E-Governance':27,
        'GIS':28,
        'HCI':29,
        'Big Data':30,
        'Other':0 }

df.Skill6 = [Skill6[item] for item in df.Skill6]


Skill7 = {'Software Engineering':1,
        'Quality Assurance':2,
        'Business Analysis':3,
        'Networking':4,
        'Management':5,
        'Research':6,
        'Lecturing':7,
        'Database':8,
        'Data Science':9,
        'Computer Science':10,
        'Information Technology':11,
        'Computer Architecture':12,
        'Distributed System':13,
        'Cloud Computing':14,
        'Data Structures and Algorithms':15,
        'Programming Languages':16,
        'Mathematics':17,
        'Operating Systems':18,
        'Multimedia, Animation and Graphic Design':19,
        'Cyber Security':20,
        'Information System':21,
        'Artificial Intelligence':22,
        'Bio-informatics':23,
        'Telecommunication':24,
        'Embedded System':25,
        'Marketing and E-Commerce':26,
        'E-Governance':27,
        'GIS':28,
        'HCI':29,
        'Big Data':30,
        'Other':0 }

df.Skill7 = [Skill7[item] for item in df.Skill7]






df.to_csv(r'D:\Academic\Level 4 - Semester 1\Research Project\Categorized Data\Skills\last.csv', index=False)

